name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mini-docker-example:latest
      
  # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Tag the Docker image
    - name: Tag the Docker image
      run: docker tag mini-docker-example:latest ghcr.io/oliver-tautz/mini-docker-example:latest

    # Push the Docker image to GitHub Container Registry
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/mini-docker-example:latest
